#!/bin/sh

### BEGIN INIT INFO
# Provides:               cuckoo
# Required-Start:         
# Required-Stop:
# Default-Start:          2 3 4 5
# Default-Stop:           0 1 6
# Short-Description:      Start/Stop the HSN2 Object Feeder Service
# Description:            Start/Stop the HSN2 Object Feeder Service
### END INIT INFO

if [ -z "`which python`" ]; then
	echo "PYTHON needs to be installed first!"
	exit 1
fi

. /lib/lsb/init-functions

NAME="Cuckoo mock"
HSN2_COMPONENT="cuckoo.py"

HSN2_COMPONENT_HOME="/opt/cuckoo/$HSN2_COMPONENT"
PIDFILE="/var/run/hsn2-$HSN2_COMPONENT.pid"

HSN2_COMPONENT_PARAMS=""

case "$1" in
	start)
		log_daemon_msg "Starting" "$NAME"
		# workaround (see redmine #6587, #6324)
		start-stop-daemon --start --chdir="/opt/cuckoo/" --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --exec /usr/bin/python -- ${HSN2_COMPONENT_HOME} ${HSN2_COMPONENT_PARAMS}
		sleep 1
		PID=`cat $PIDFILE`
		TEST=`ps ax | grep $PID | grep python | sed -e 's/^ *//' | cut -d' ' -f1`
		if [ -n "$TEST" ]; then
		# original code
		#if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --exec /usr/bin/python -- ${HSN2_COMPONENT_HOME} $HSN2_COMPONENT_PARAMS; then
			log_end_msg 0
		else
			log_end_msg 1
			echo "" > $PIDFILE
		fi
		;;

	stop)
		log_daemon_msg "Stopping" "$NAME"
		if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
			log_end_msg 0
			echo "" > $PIDFILE
			#rm -f $PIDFILE
		else
			log_end_msg 1
		fi
		;;

	status)
		status_of_proc -p $PIDFILE "$JAVA" "$NAME" && exit 0 || exit $?
		;;
esac
exit 0
